# Generated by Django 3.1.7 on 2021-03-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trellouser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Profile picture'),
        ),
    ]
