# Generated by Django 3.1.7 on 2021-08-16 17:30

import apps.ban_for_ip.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannedIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip', models.GenericIPAddressField()),
                ('expire_date', models.DateTimeField(default=apps.ban_for_ip.models._default_ban_ttl)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
