# Generated by Django 3.1.7 on 2021-03-25 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterUniqueTogether(
            name='board',
            unique_together={('name', 'owner')},
        ),
    ]
