# Generated by Django 3.1.7 on 2021-04-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20210419_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='col',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, null=True),
        ),
    ]
